server:
  port: 8060
  servlet:
    context-path: /student-service-provider

spring:
  application:
    name: student-service-provider
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
    defaultPropertyInclusion: non_null   #非空属性才序列化
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false #未定义的key不序列化
#  对返回的时间进行格式化
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/student_service?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    variables:
      logTablename: log2019  // log 的表名

# 显示 sql， 配置到 mapper 所在目录
logging:
  level:
    org.hibernate.SQL: INFO
    com.sse: INFO

eureka:
  instance:
    preferIpAddress: true
    hostname: 127.0.0.1
    instanceId: ${spring.cloud.client.ipAddress:127.0.0.1}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.port:8010}/eureka/
    enabled: false

secure:
  key: 1234qwer!@#