server:
  port: 8060
  servlet:
    context-path: /student-service-provider
  connection-timeout: 2s # 停止数据发送后多久断开连接
  tomcat:
    max-connections: 5000 #最大连接数
    max-threads: 100  # 最大线程数


spring:
  application:
    name: student-service-provider
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
    defaultPropertyInclusion: non_null   #非空属性才序列化
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false #未定义的key不序列化
#  对返回的时间进行格式化
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/student_service?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    variables:
      logTablename: log2019 # log 的表名

# 显示 sql， 配置到 mapper 所在目录
# 方式一：
#logging:
#  level:
#    com.sse.adapter.mybatis: DEBUG

# 方式二：
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  instance:
    preferIpAddress: true
    hostname: 127.0.0.1
    instanceId: ${spring.cloud.client.ipAddress:127.0.0.1}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.port:8010}/eureka/
    enabled: false

secure:
  key: 1234qwer!@#